"""empty message

Revision ID: b2bd5c68d924
Revises: 550aab7c677f
Create Date: 2024-01-07 18:33:17.421181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2bd5c68d924'
down_revision: Union[str, None] = '550aab7c677f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ResetPassword', sa.Column('email', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'ResetPassword', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ResetPassword', type_='unique')
    op.drop_column('ResetPassword', 'email')
    # ### end Alembic commands ###
